### ISSUE TITLE
ListTasks should return only minimum amount of data instead the full details.

### ISSUE THREAD

**Issue by chrisli30** [AvaProtocol/EigenLayer-AVS#43]
I see that currently full task data are being returned in the TaskList, but for a list function we only need a minimum amount data. What we really need is the ids, but let’s return the below details in list:
```
TaskId
Creator(owner)
Created Datetime
Status: Active, Completed or Canceled
TriggerType: EventTrigger or TimeTrigger
```

![CleanShot 2024-12-06 at 12 14 09@2x](https://github.com/user-attachments/assets/cd806716-5212-45c4-9fc7-edd3023ab35b)

**Comment by v9n** [comment]
I had it before that way to only return task id, but you want to change it. This is the issue https://github.com/AvaProtocol/ava-sdk-js/issues/28 where you want it to return everything.

```
@v9n, for simplicity I suggest we return the entire task data in listTasks for now, and trim the response later, when request load increases.
```

let me know which way you want to proceed. I do prefer to just return Task ID in list.

**Comment by chrisli30** [comment]
> I had it before that way to only return task id, but you want to change it. This is the issue [AvaProtocol/ava-sdk-js#28](https://github.com/AvaProtocol/ava-sdk-js/issues/28) where you want it to return everything.
> 
> ```
> @v9n, for simplicity I suggest we return the entire task data in listTasks for now, and trim the response later, when request load increases.
> ```
> 
> let me know which way you want to proceed. I do prefer to just return what you wrote above in listTasks.
> 
> ```
> TaskId
> Creator(owner)
> Created Datetime
> Status: Active, Completed or Canceled
> TriggerType: EventTrigger or TimeTrigger
> ```

Right, returning a full Task object was my call, but after checking out the response I find it too much information. I saw that they are being simplified in #53 👍
