### ISSUE TITLE
Create an API that returns a list of execution by taskId

### ISSUE THREAD

**Issue by chrisli30** [AvaProtocol/EigenLayer-AVS#45]
If one task contain 1000 executions, getting the details of the task will either break or take very long. Also, the current embedded two-tier list tasks->executions make returning lists problematic.

I think we should create an API for getting only executions, with filter **by taskId or wallet_address**, and pagination. The task.executions in task details can return only most recent 5 transactions. On UI we also have the need to retun the most recent executions.

Since this is an API format change, it’s better to get it right in the beginnig.

**Comment by v9n** [comment]
Yes, I had implement these already but haven't push it because it change the sdk. Will have both of these by eod.

**Comment by v9n** [comment]
dup of #44

**Comment by v9n** [comment]
Implemented in https://github.com/AvaProtocol/EigenLayer-AVS/commit/97c45a4ea9efebf6c921d2dd33d06f3b34e093fe

Example of API usage: https://github.com/AvaProtocol/EigenLayer-AVS/blob/main/examples/example.js#L147
