### ISSUE TITLE
Nit pick: rename FixedEpochCondition to be more comprehensive

### ISSUE THREAD

**Issue by chrisli30** [AvaProtocol/EigenLayer-AVS#51]
Regarding,
```
message FixedEpochCondition {
  repeated int64 epochs = 1;
}
```
I suggest us to rename the struct name of `FixedEpochCondition` to `FixedTimeCondition`, due to the below reasons:
1. FixedTime is more general and straight-forward.
2. `epochs` is already in its property and very clear, so there’s no need to do write another Epoch before it. 
3. Just in case we put some other time related properties in it. `Time` would be more general.

**Comment by v9n** [comment]
Fixed in #58
