### ISSUE TITLE
Suggest to rename the run_inline variable in TriggerMark

### ISSUE THREAD

**Issue by chrisli30** [AvaProtocol/EigenLayer-AVS#69]
The `inline` name sounds not very familiar too me. I couldn’t understand it at first, but after lookup I found the "Inline Execution in Asynchronous Systems". However, there are inline functions in C++/C# and inline css in HTML. It has too many meanings.

From your description, I think we should just rename it to `is_blocking`, and set the default value to `false`. 

```
/ when setting run_inline=true, the execution run in the same request. the request is blocked until the execution is done
  // setting to false, the task will be execute in our normal queueu system, and the request won't block.
  // default value is false, for interact testing, set this to true
```

**Comment by v9n** [comment]
Address in https://github.com/AvaProtocol/EigenLayer-AVS/pull/68
