### ISSUE TITLE
When setting maxExecution, use -1 to denote unlimited 

### ISSUE THREAD

**Issue by v9n** [AvaProtocol/EigenLayer-AVS#72]
I'm not really sure what possessed me but I used 0 to denote unlimited when set maxExecution.

it is such a bad idea. because it's the default value if not set. Mean if someone use this API directly, not setting that we will run indefinetely where as maybe they just want to run only once.

I think we should change this to `-1`, if user _not set this value_, or set it to 0, the server should reject.

**Comment by chrisli30** [comment]
In your proposed design, 0 is always rejected and not used, so it doesn’t hurt to use the value 0.

I think we designed the default to be 0, meaning we want them to keep running the task. The UI will always alert them about the indefinite run.

I’d say no change to this.
